#############################################################################
# Makefile for building: bin/PlantNurseryGUI
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  app.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile app.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -IStaffWindows -ICustomerWindows -ICommon -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/moc -Ibuild/ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PlantNurseryGUI1.0.0
DISTDIR = /home/obedm/second-year/COS214_project/CodeBlooded/build/obj/PlantNurseryGUI1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = Cactus.cpp \
		CactusFactory.cpp \
		Caretaker.cpp \
		Command.cpp \
		Customer.cpp \
		CustomerCommand.cpp \
		CustomerFacade.cpp \
		DeadCommand.cpp \
		DeadHandler.cpp \
		DeadMonitor.cpp \
		DeadState.cpp \
		DeleteQueryBuilder.cpp \
		Save10Discount.cpp \
		BulkDiscount.cpp \
		FertilizedState.cpp \
		FertilizerCommand.cpp \
		FertilizerHandler.cpp \
		FertilizerMonitor.cpp \
		GerminationState.cpp \
		GetPlantCommand.cpp \
		GiftWrap.cpp \
		GreenHouseFacade.cpp \
		GreenHouseInventory.cpp \
		HydratedState.cpp \
		InsertQueryBuilder.cpp \
		Item.cpp \
		MatureState.cpp \
		NonFertilizerState.cpp \
		NormalPrice.cpp \
		NotHydratedState.cpp \
		Order.cpp \
		OrderMemento.cpp \
		Plant.cpp \
		PlantCommand.cpp \
		PlantDecorator.cpp \
		PlantFactory.cpp \
		PlantGroup.cpp \
		PlantMonitor.cpp \
		PlantSnapshot.cpp \
		ProxyGreenHouseInventory.cpp \
		QueryBuilder.cpp \
		QueryProduct.cpp \
		QueueIterator.cpp \
		RealGreenHouseInventory.cpp \
		Receipt.cpp \
		RedPot.cpp \
		Ribbon.cpp \
		Rose.cpp \
		RoseFactory.cpp \
		SalesHandler.cpp \
		SaplingState.cpp \
		Scent.cpp \
		SeedState.cpp \
		SelectQueryBuilder.cpp \
		StaffHandler.cpp \
		StaffSystem.cpp \
		Sunflower.cpp \
		SunflowerFactory.cpp \
		Water.cpp \
		WaterCommand.cpp \
		WaterHandler.cpp \
		WaterMonitor.cpp \
		main.cpp \
		Common/LoginDialog.cpp \
		CustomerWindows/CustomerMainWindow.cpp \
		CustomerWindows/ReturnOrderDialog.cpp \
		CustomerWindows/ReceiptDialog.cpp \
		StaffWindows/StaffMainWindow.cpp \
		StaffWindows/PlantManagementWidget.cpp \
		StaffWindows/StaffManagementWidget.cpp build/rcc/qrc_resources.cpp \
		build/moc/moc_LoginDialog.cpp \
		build/moc/moc_CustomerMainWindow.cpp \
		build/moc/moc_ReturnOrderDialog.cpp \
		build/moc/moc_ReceiptDialog.cpp \
		build/moc/moc_StaffMainWindow.cpp \
		build/moc/moc_PlantManagementWidget.cpp \
		build/moc/moc_StaffManagementWidget.cpp
OBJECTS       = build/obj/Cactus.o \
		build/obj/CactusFactory.o \
		build/obj/Caretaker.o \
		build/obj/Command.o \
		build/obj/Customer.o \
		build/obj/CustomerCommand.o \
		build/obj/CustomerFacade.o \
		build/obj/DeadCommand.o \
		build/obj/DeadHandler.o \
		build/obj/DeadMonitor.o \
		build/obj/DeadState.o \
		build/obj/DeleteQueryBuilder.o \
		build/obj/Save10Discount.o \
		build/obj/BulkDiscount.o \
		build/obj/FertilizedState.o \
		build/obj/FertilizerCommand.o \
		build/obj/FertilizerHandler.o \
		build/obj/FertilizerMonitor.o \
		build/obj/GerminationState.o \
		build/obj/GetPlantCommand.o \
		build/obj/GiftWrap.o \
		build/obj/GreenHouseFacade.o \
		build/obj/GreenHouseInventory.o \
		build/obj/HydratedState.o \
		build/obj/InsertQueryBuilder.o \
		build/obj/Item.o \
		build/obj/MatureState.o \
		build/obj/NonFertilizerState.o \
		build/obj/NormalPrice.o \
		build/obj/NotHydratedState.o \
		build/obj/Order.o \
		build/obj/OrderMemento.o \
		build/obj/Plant.o \
		build/obj/PlantCommand.o \
		build/obj/PlantDecorator.o \
		build/obj/PlantFactory.o \
		build/obj/PlantGroup.o \
		build/obj/PlantMonitor.o \
		build/obj/PlantSnapshot.o \
		build/obj/ProxyGreenHouseInventory.o \
		build/obj/QueryBuilder.o \
		build/obj/QueryProduct.o \
		build/obj/QueueIterator.o \
		build/obj/RealGreenHouseInventory.o \
		build/obj/Receipt.o \
		build/obj/RedPot.o \
		build/obj/Ribbon.o \
		build/obj/Rose.o \
		build/obj/RoseFactory.o \
		build/obj/SalesHandler.o \
		build/obj/SaplingState.o \
		build/obj/Scent.o \
		build/obj/SeedState.o \
		build/obj/SelectQueryBuilder.o \
		build/obj/StaffHandler.o \
		build/obj/StaffSystem.o \
		build/obj/Sunflower.o \
		build/obj/SunflowerFactory.o \
		build/obj/Water.o \
		build/obj/WaterCommand.o \
		build/obj/WaterHandler.o \
		build/obj/WaterMonitor.o \
		build/obj/main.o \
		build/obj/LoginDialog.o \
		build/obj/CustomerMainWindow.o \
		build/obj/ReturnOrderDialog.o \
		build/obj/ReceiptDialog.o \
		build/obj/StaffMainWindow.o \
		build/obj/PlantManagementWidget.o \
		build/obj/StaffManagementWidget.o \
		build/obj/qrc_resources.o \
		build/obj/moc_LoginDialog.o \
		build/obj/moc_CustomerMainWindow.o \
		build/obj/moc_ReturnOrderDialog.o \
		build/obj/moc_ReceiptDialog.o \
		build/obj/moc_StaffMainWindow.o \
		build/obj/moc_PlantManagementWidget.o \
		build/obj/moc_StaffManagementWidget.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		app.pro Cactus.h \
		CactusFactory.h \
		Caretaker.h \
		Command.h \
		Customer.h \
		CustomerCommand.h \
		CustomerFacade.h \
		DeadCommand.h \
		DeadHandler.h \
		DeadMonitor.h \
		DeadState.h \
		DeleteQueryBuilder.h \
		Save10Discount.h \
		BulkDiscount.h \
		FertilizedState.h \
		Fertilizer.h \
		FertilizerCommand.h \
		FertilizerHandler.h \
		FertilizerMonitor.h \
		GerminationState.h \
		GetPlantCommand.h \
		GiftWrap.h \
		GreenHouseFacade.h \
		GreenHouseInventory.h \
		HydratedState.h \
		InsertQueryBuilder.h \
		Item.h \
		MatureState.h \
		NonFertilizerState.h \
		NormalPrice.h \
		NotHydratedState.h \
		Order.h \
		OrderMemento.h \
		Plant.h \
		PlantCommand.h \
		PlantComponent.h \
		PlantDecorator.h \
		PlantFactory.h \
		PlantGroup.h \
		PlantGrowthState.h \
		PlantMonitor.h \
		PlantSnapshot.h \
		PriceStrategies.h \
		ProxyGreenHouseInventory.h \
		QueryBuilder.h \
		QueryProduct.h \
		QueueIterator.h \
		RealGreenHouseInventory.h \
		Receipt.h \
		RedPot.h \
		Ribbon.h \
		Rose.h \
		RoseFactory.h \
		SalesHandler.h \
		SaplingState.h \
		Scent.h \
		SeedState.h \
		SelectQueryBuilder.h \
		StaffHandler.h \
		StaffSystem.h \
		Sunflower.h \
		SunflowerFactory.h \
		Water.h \
		WaterCommand.h \
		WaterHandler.h \
		WaterMonitor.h \
		Common/LoginDialog.h \
		CustomerWindows/CustomerMainWindow.h \
		CustomerWindows/ReturnOrderDialog.h \
		CustomerWindows/ReceiptDialog.h \
		StaffWindows/StaffMainWindow.h \
		StaffWindows/PlantManagementWidget.h \
		StaffWindows/StaffManagementWidget.h Cactus.cpp \
		CactusFactory.cpp \
		Caretaker.cpp \
		Command.cpp \
		Customer.cpp \
		CustomerCommand.cpp \
		CustomerFacade.cpp \
		DeadCommand.cpp \
		DeadHandler.cpp \
		DeadMonitor.cpp \
		DeadState.cpp \
		DeleteQueryBuilder.cpp \
		Save10Discount.cpp \
		BulkDiscount.cpp \
		FertilizedState.cpp \
		FertilizerCommand.cpp \
		FertilizerHandler.cpp \
		FertilizerMonitor.cpp \
		GerminationState.cpp \
		GetPlantCommand.cpp \
		GiftWrap.cpp \
		GreenHouseFacade.cpp \
		GreenHouseInventory.cpp \
		HydratedState.cpp \
		InsertQueryBuilder.cpp \
		Item.cpp \
		MatureState.cpp \
		NonFertilizerState.cpp \
		NormalPrice.cpp \
		NotHydratedState.cpp \
		Order.cpp \
		OrderMemento.cpp \
		Plant.cpp \
		PlantCommand.cpp \
		PlantDecorator.cpp \
		PlantFactory.cpp \
		PlantGroup.cpp \
		PlantMonitor.cpp \
		PlantSnapshot.cpp \
		ProxyGreenHouseInventory.cpp \
		QueryBuilder.cpp \
		QueryProduct.cpp \
		QueueIterator.cpp \
		RealGreenHouseInventory.cpp \
		Receipt.cpp \
		RedPot.cpp \
		Ribbon.cpp \
		Rose.cpp \
		RoseFactory.cpp \
		SalesHandler.cpp \
		SaplingState.cpp \
		Scent.cpp \
		SeedState.cpp \
		SelectQueryBuilder.cpp \
		StaffHandler.cpp \
		StaffSystem.cpp \
		Sunflower.cpp \
		SunflowerFactory.cpp \
		Water.cpp \
		WaterCommand.cpp \
		WaterHandler.cpp \
		WaterMonitor.cpp \
		main.cpp \
		Common/LoginDialog.cpp \
		CustomerWindows/CustomerMainWindow.cpp \
		CustomerWindows/ReturnOrderDialog.cpp \
		CustomerWindows/ReceiptDialog.cpp \
		StaffWindows/StaffMainWindow.cpp \
		StaffWindows/PlantManagementWidget.cpp \
		StaffWindows/StaffManagementWidget.cpp
QMAKE_TARGET  = PlantNurseryGUI
DESTDIR       = bin/
TARGET        = bin/PlantNurseryGUI


first: all
####### Build rules

bin/PlantNurseryGUI: build/ui/ui_LoginDialog.h build/ui/ui_CustomerMainWindow.h build/ui/ui_ReturnOrderDialog.h build/ui/ui_ReceiptDialog.h build/ui/ui_StaffMainWindow.h build/ui/ui_PlantManagementWidget.h build/ui/ui_StaffManagementWidget.h $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: app.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		app.pro \
		resources.qrc
	$(QMAKE) -o Makefile app.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
app.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile app.pro

qmake_all: FORCE


all: Makefile bin/PlantNurseryGUI

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Cactus.h CactusFactory.h Caretaker.h Command.h Customer.h CustomerCommand.h CustomerFacade.h DeadCommand.h DeadHandler.h DeadMonitor.h DeadState.h DeleteQueryBuilder.h Save10Discount.h BulkDiscount.h FertilizedState.h Fertilizer.h FertilizerCommand.h FertilizerHandler.h FertilizerMonitor.h GerminationState.h GetPlantCommand.h GiftWrap.h GreenHouseFacade.h GreenHouseInventory.h HydratedState.h InsertQueryBuilder.h Item.h MatureState.h NonFertilizerState.h NormalPrice.h NotHydratedState.h Order.h OrderMemento.h Plant.h PlantCommand.h PlantComponent.h PlantDecorator.h PlantFactory.h PlantGroup.h PlantGrowthState.h PlantMonitor.h PlantSnapshot.h PriceStrategies.h ProxyGreenHouseInventory.h QueryBuilder.h QueryProduct.h QueueIterator.h RealGreenHouseInventory.h Receipt.h RedPot.h Ribbon.h Rose.h RoseFactory.h SalesHandler.h SaplingState.h Scent.h SeedState.h SelectQueryBuilder.h StaffHandler.h StaffSystem.h Sunflower.h SunflowerFactory.h Water.h WaterCommand.h WaterHandler.h WaterMonitor.h Common/LoginDialog.h CustomerWindows/CustomerMainWindow.h CustomerWindows/ReturnOrderDialog.h CustomerWindows/ReceiptDialog.h StaffWindows/StaffMainWindow.h StaffWindows/PlantManagementWidget.h StaffWindows/StaffManagementWidget.h $(DISTDIR)/
	$(COPY_FILE) --parents Cactus.cpp CactusFactory.cpp Caretaker.cpp Command.cpp Customer.cpp CustomerCommand.cpp CustomerFacade.cpp DeadCommand.cpp DeadHandler.cpp DeadMonitor.cpp DeadState.cpp DeleteQueryBuilder.cpp Save10Discount.cpp BulkDiscount.cpp FertilizedState.cpp FertilizerCommand.cpp FertilizerHandler.cpp FertilizerMonitor.cpp GerminationState.cpp GetPlantCommand.cpp GiftWrap.cpp GreenHouseFacade.cpp GreenHouseInventory.cpp HydratedState.cpp InsertQueryBuilder.cpp Item.cpp MatureState.cpp NonFertilizerState.cpp NormalPrice.cpp NotHydratedState.cpp Order.cpp OrderMemento.cpp Plant.cpp PlantCommand.cpp PlantDecorator.cpp PlantFactory.cpp PlantGroup.cpp PlantMonitor.cpp PlantSnapshot.cpp ProxyGreenHouseInventory.cpp QueryBuilder.cpp QueryProduct.cpp QueueIterator.cpp RealGreenHouseInventory.cpp Receipt.cpp RedPot.cpp Ribbon.cpp Rose.cpp RoseFactory.cpp SalesHandler.cpp SaplingState.cpp Scent.cpp SeedState.cpp SelectQueryBuilder.cpp StaffHandler.cpp StaffSystem.cpp Sunflower.cpp SunflowerFactory.cpp Water.cpp WaterCommand.cpp WaterHandler.cpp WaterMonitor.cpp main.cpp Common/LoginDialog.cpp CustomerWindows/CustomerMainWindow.cpp CustomerWindows/ReturnOrderDialog.cpp CustomerWindows/ReceiptDialog.cpp StaffWindows/StaffMainWindow.cpp StaffWindows/PlantManagementWidget.cpp StaffWindows/StaffManagementWidget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Common/LoginDialog.ui CustomerWindows/CustomerMainWindow.ui CustomerWindows/ReturnOrderDialog.ui CustomerWindows/ReceiptDialog.ui StaffWindows/StaffMainWindow.ui StaffWindows/PlantManagementWidget.ui StaffWindows/StaffManagementWidget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/rcc/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/rcc/qrc_resources.cpp
build/rcc/qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		styles.qss \
		resources/font/PressStart2P.ttf
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o build/rcc/qrc_resources.cpp

compiler_moc_predefs_make_all: build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc/moc_predefs.h
build/moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o build/moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc/moc_LoginDialog.cpp build/moc/moc_CustomerMainWindow.cpp build/moc/moc_ReturnOrderDialog.cpp build/moc/moc_ReceiptDialog.cpp build/moc/moc_StaffMainWindow.cpp build/moc/moc_PlantManagementWidget.cpp build/moc/moc_StaffManagementWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_LoginDialog.cpp build/moc/moc_CustomerMainWindow.cpp build/moc/moc_ReturnOrderDialog.cpp build/moc/moc_ReceiptDialog.cpp build/moc/moc_StaffMainWindow.cpp build/moc/moc_PlantManagementWidget.cpp build/moc/moc_StaffManagementWidget.cpp
build/moc/moc_LoginDialog.cpp: Common/LoginDialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/obedm/second-year/COS214_project/CodeBlooded/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/obedm/second-year/COS214_project/CodeBlooded -I/home/obedm/second-year/COS214_project/CodeBlooded/StaffWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/CustomerWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/Common -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Common/LoginDialog.h -o build/moc/moc_LoginDialog.cpp

build/moc/moc_CustomerMainWindow.cpp: CustomerWindows/CustomerMainWindow.h \
		CustomerFacade.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		Caretaker.h \
		OrderMemento.h \
		Order.h \
		PlantGroup.h \
		PriceStrategies.h \
		Receipt.h \
		Customer.h \
		QueryBuilder.h \
		SelectQueryBuilder.h \
		PlantDecorator.h \
		NormalPrice.h \
		Save10Discount.h \
		BulkDiscount.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/obedm/second-year/COS214_project/CodeBlooded/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/obedm/second-year/COS214_project/CodeBlooded -I/home/obedm/second-year/COS214_project/CodeBlooded/StaffWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/CustomerWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/Common -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include CustomerWindows/CustomerMainWindow.h -o build/moc/moc_CustomerMainWindow.cpp

build/moc/moc_ReturnOrderDialog.cpp: CustomerWindows/ReturnOrderDialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/obedm/second-year/COS214_project/CodeBlooded/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/obedm/second-year/COS214_project/CodeBlooded -I/home/obedm/second-year/COS214_project/CodeBlooded/StaffWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/CustomerWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/Common -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include CustomerWindows/ReturnOrderDialog.h -o build/moc/moc_ReturnOrderDialog.cpp

build/moc/moc_ReceiptDialog.cpp: CustomerWindows/ReceiptDialog.h \
		Order.h \
		PlantGroup.h \
		PlantComponent.h \
		PriceStrategies.h \
		OrderMemento.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Receipt.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/obedm/second-year/COS214_project/CodeBlooded/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/obedm/second-year/COS214_project/CodeBlooded -I/home/obedm/second-year/COS214_project/CodeBlooded/StaffWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/CustomerWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/Common -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include CustomerWindows/ReceiptDialog.h -o build/moc/moc_ReceiptDialog.cpp

build/moc/moc_StaffMainWindow.cpp: StaffWindows/StaffMainWindow.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/obedm/second-year/COS214_project/CodeBlooded/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/obedm/second-year/COS214_project/CodeBlooded -I/home/obedm/second-year/COS214_project/CodeBlooded/StaffWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/CustomerWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/Common -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include StaffWindows/StaffMainWindow.h -o build/moc/moc_StaffMainWindow.cpp

build/moc/moc_PlantManagementWidget.cpp: StaffWindows/PlantManagementWidget.h \
		GreenHouseFacade.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		PlantFactory.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		FertilizerMonitor.h \
		DeadMonitor.h \
		RoseFactory.h \
		SunflowerFactory.h \
		CactusFactory.h \
		WaterHandler.h \
		FertilizerHandler.h \
		DeadHandler.h \
		SalesHandler.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/obedm/second-year/COS214_project/CodeBlooded/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/obedm/second-year/COS214_project/CodeBlooded -I/home/obedm/second-year/COS214_project/CodeBlooded/StaffWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/CustomerWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/Common -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include StaffWindows/PlantManagementWidget.h -o build/moc/moc_PlantManagementWidget.cpp

build/moc/moc_StaffManagementWidget.cpp: StaffWindows/StaffManagementWidget.h \
		GreenHouseFacade.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		PlantFactory.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		FertilizerMonitor.h \
		DeadMonitor.h \
		RoseFactory.h \
		SunflowerFactory.h \
		CactusFactory.h \
		WaterHandler.h \
		FertilizerHandler.h \
		DeadHandler.h \
		SalesHandler.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/obedm/second-year/COS214_project/CodeBlooded/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/obedm/second-year/COS214_project/CodeBlooded -I/home/obedm/second-year/COS214_project/CodeBlooded/StaffWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/CustomerWindows -I/home/obedm/second-year/COS214_project/CodeBlooded/Common -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include StaffWindows/StaffManagementWidget.h -o build/moc/moc_StaffManagementWidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui/ui_LoginDialog.h build/ui/ui_CustomerMainWindow.h build/ui/ui_ReturnOrderDialog.h build/ui/ui_ReceiptDialog.h build/ui/ui_StaffMainWindow.h build/ui/ui_PlantManagementWidget.h build/ui/ui_StaffManagementWidget.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui/ui_LoginDialog.h build/ui/ui_CustomerMainWindow.h build/ui/ui_ReturnOrderDialog.h build/ui/ui_ReceiptDialog.h build/ui/ui_StaffMainWindow.h build/ui/ui_PlantManagementWidget.h build/ui/ui_StaffManagementWidget.h
build/ui/ui_LoginDialog.h: Common/LoginDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Common/LoginDialog.ui -o build/ui/ui_LoginDialog.h

build/ui/ui_CustomerMainWindow.h: CustomerWindows/CustomerMainWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic CustomerWindows/CustomerMainWindow.ui -o build/ui/ui_CustomerMainWindow.h

build/ui/ui_ReturnOrderDialog.h: CustomerWindows/ReturnOrderDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic CustomerWindows/ReturnOrderDialog.ui -o build/ui/ui_ReturnOrderDialog.h

build/ui/ui_ReceiptDialog.h: CustomerWindows/ReceiptDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic CustomerWindows/ReceiptDialog.ui -o build/ui/ui_ReceiptDialog.h

build/ui/ui_StaffMainWindow.h: StaffWindows/StaffMainWindow.ui \
		/usr/lib/qt5/bin/uic \
		StaffWindows/PlantManagementWidget.h \
		StaffWindows/StaffManagementWidget.h \
		GreenHouseFacade.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		PlantFactory.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		FertilizerMonitor.h \
		DeadMonitor.h \
		RoseFactory.h \
		SunflowerFactory.h \
		CactusFactory.h \
		WaterHandler.h \
		FertilizerHandler.h \
		DeadHandler.h \
		SalesHandler.h \
		GreenHouseFacade.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		PlantFactory.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		FertilizerMonitor.h \
		DeadMonitor.h \
		RoseFactory.h \
		SunflowerFactory.h \
		CactusFactory.h \
		WaterHandler.h \
		FertilizerHandler.h \
		DeadHandler.h \
		SalesHandler.h
	/usr/lib/qt5/bin/uic StaffWindows/StaffMainWindow.ui -o build/ui/ui_StaffMainWindow.h

build/ui/ui_PlantManagementWidget.h: StaffWindows/PlantManagementWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic StaffWindows/PlantManagementWidget.ui -o build/ui/ui_PlantManagementWidget.h

build/ui/ui_StaffManagementWidget.h: StaffWindows/StaffManagementWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic StaffWindows/StaffManagementWidget.ui -o build/ui/ui_StaffManagementWidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/obj/Cactus.o: Cactus.cpp Cactus.h \
		Plant.h \
		PlantComponent.h \
		PlantGrowthState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Cactus.o Cactus.cpp

build/obj/CactusFactory.o: CactusFactory.cpp CactusFactory.h \
		PlantFactory.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		Plant.h \
		PlantComponent.h \
		FertilizerMonitor.h \
		DeadMonitor.h \
		Cactus.h \
		PlantGrowthState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/CactusFactory.o CactusFactory.cpp

build/obj/Caretaker.o: Caretaker.cpp Caretaker.h \
		OrderMemento.h \
		Order.h \
		PlantGroup.h \
		PlantComponent.h \
		PriceStrategies.h \
		Receipt.h \
		Plant.h \
		PlantSnapshot.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		GreenHouseInventory.h \
		Item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Caretaker.o Caretaker.cpp

build/obj/Command.o: Command.cpp Command.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Command.o Command.cpp

build/obj/Customer.o: Customer.cpp Customer.h \
		QueryBuilder.h \
		Plant.h \
		PlantComponent.h \
		SelectQueryBuilder.h \
		QueryProduct.h \
		PlantGrowthState.h \
		GreenHouseInventory.h \
		PlantSnapshot.h \
		Cactus.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		ProxyGreenHouseInventory.h \
		SeedState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Customer.o Customer.cpp

build/obj/CustomerCommand.o: CustomerCommand.cpp CustomerCommand.h \
		Command.h \
		Customer.h \
		QueryBuilder.h \
		Plant.h \
		PlantComponent.h \
		SelectQueryBuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/CustomerCommand.o CustomerCommand.cpp

build/obj/CustomerFacade.o: CustomerFacade.cpp CustomerFacade.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		Caretaker.h \
		OrderMemento.h \
		Order.h \
		PlantGroup.h \
		PriceStrategies.h \
		Receipt.h \
		Customer.h \
		QueryBuilder.h \
		SelectQueryBuilder.h \
		PlantDecorator.h \
		NormalPrice.h \
		Save10Discount.h \
		BulkDiscount.h \
		RedPot.h \
		Ribbon.h \
		Scent.h \
		GiftWrap.h \
		QueryProduct.h \
		SeedState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/CustomerFacade.o CustomerFacade.cpp

build/obj/DeadCommand.o: DeadCommand.cpp DeadCommand.h \
		PlantCommand.h \
		Command.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/DeadCommand.o DeadCommand.cpp

build/obj/DeadHandler.o: DeadHandler.cpp DeadHandler.h \
		StaffHandler.h \
		Command.h \
		DeadCommand.h \
		PlantCommand.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/DeadHandler.o DeadHandler.cpp

build/obj/DeadMonitor.o: DeadMonitor.cpp DeadMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		Plant.h \
		PlantComponent.h \
		DeadCommand.h \
		PlantCommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/DeadMonitor.o DeadMonitor.cpp

build/obj/DeadState.o: DeadState.cpp DeadState.h \
		PlantGrowthState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/DeadState.o DeadState.cpp

build/obj/DeleteQueryBuilder.o: DeleteQueryBuilder.cpp DeleteQueryBuilder.h \
		QueryBuilder.h \
		Plant.h \
		PlantComponent.h \
		QueryProduct.h \
		PlantGrowthState.h \
		GreenHouseInventory.h \
		PlantSnapshot.h \
		Cactus.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		ProxyGreenHouseInventory.h \
		SeedState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/DeleteQueryBuilder.o DeleteQueryBuilder.cpp

build/obj/Save10Discount.o: Save10Discount.cpp Save10Discount.h \
		PriceStrategies.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Save10Discount.o Save10Discount.cpp

build/obj/BulkDiscount.o: BulkDiscount.cpp BulkDiscount.h \
		PriceStrategies.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/BulkDiscount.o BulkDiscount.cpp

build/obj/FertilizedState.o: FertilizedState.cpp FertilizedState.h \
		Fertilizer.h \
		NonFertilizerState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/FertilizedState.o FertilizedState.cpp

build/obj/FertilizerCommand.o: FertilizerCommand.cpp FertilizerCommand.h \
		PlantCommand.h \
		Command.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/FertilizerCommand.o FertilizerCommand.cpp

build/obj/FertilizerHandler.o: FertilizerHandler.cpp FertilizerHandler.h \
		StaffHandler.h \
		Command.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/FertilizerHandler.o FertilizerHandler.cpp

build/obj/FertilizerMonitor.o: FertilizerMonitor.cpp FertilizerMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		Plant.h \
		PlantComponent.h \
		FertilizerCommand.h \
		PlantCommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/FertilizerMonitor.o FertilizerMonitor.cpp

build/obj/GerminationState.o: GerminationState.cpp GerminationState.h \
		PlantGrowthState.h \
		SaplingState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/GerminationState.o GerminationState.cpp

build/obj/GetPlantCommand.o: GetPlantCommand.cpp GetPlantCommand.h \
		CustomerCommand.h \
		Command.h \
		Customer.h \
		QueryBuilder.h \
		Plant.h \
		PlantComponent.h \
		SelectQueryBuilder.h \
		Order.h \
		PlantGroup.h \
		PriceStrategies.h \
		OrderMemento.h \
		PlantSnapshot.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Receipt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/GetPlantCommand.o GetPlantCommand.cpp

build/obj/GiftWrap.o: GiftWrap.cpp GiftWrap.h \
		PlantDecorator.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/GiftWrap.o GiftWrap.cpp

build/obj/GreenHouseFacade.o: GreenHouseFacade.cpp GreenHouseFacade.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		PlantFactory.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		FertilizerMonitor.h \
		DeadMonitor.h \
		RoseFactory.h \
		SunflowerFactory.h \
		CactusFactory.h \
		WaterHandler.h \
		FertilizerHandler.h \
		DeadHandler.h \
		SalesHandler.h \
		Common/SharedInstances.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/GreenHouseFacade.o GreenHouseFacade.cpp

build/obj/GreenHouseInventory.o: GreenHouseInventory.cpp GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/GreenHouseInventory.o GreenHouseInventory.cpp

build/obj/HydratedState.o: HydratedState.cpp HydratedState.h \
		Water.h \
		PlantGrowthState.h \
		NotHydratedState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/HydratedState.o HydratedState.cpp

build/obj/InsertQueryBuilder.o: InsertQueryBuilder.cpp InsertQueryBuilder.h \
		QueryBuilder.h \
		Plant.h \
		PlantComponent.h \
		QueryProduct.h \
		PlantGrowthState.h \
		GreenHouseInventory.h \
		PlantSnapshot.h \
		Cactus.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		ProxyGreenHouseInventory.h \
		SeedState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/InsertQueryBuilder.o InsertQueryBuilder.cpp

build/obj/Item.o: Item.cpp Item.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Item.o Item.cpp

build/obj/MatureState.o: MatureState.cpp MatureState.h \
		PlantGrowthState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/MatureState.o MatureState.cpp

build/obj/NonFertilizerState.o: NonFertilizerState.cpp NonFertilizerState.h \
		Fertilizer.h \
		FertilizedState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/NonFertilizerState.o NonFertilizerState.cpp

build/obj/NormalPrice.o: NormalPrice.cpp NormalPrice.h \
		PriceStrategies.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/NormalPrice.o NormalPrice.cpp

build/obj/NotHydratedState.o: NotHydratedState.cpp NotHydratedState.h \
		Water.h \
		PlantGrowthState.h \
		HydratedState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/NotHydratedState.o NotHydratedState.cpp

build/obj/Order.o: Order.cpp Order.h \
		PlantGroup.h \
		PlantComponent.h \
		PriceStrategies.h \
		OrderMemento.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Receipt.h \
		NormalPrice.h \
		BulkDiscount.h \
		Save10Discount.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Order.o Order.cpp

build/obj/OrderMemento.o: OrderMemento.cpp OrderMemento.h \
		Order.h \
		PlantGroup.h \
		PlantComponent.h \
		PriceStrategies.h \
		Receipt.h \
		Plant.h \
		PlantSnapshot.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/OrderMemento.o OrderMemento.cpp

build/obj/Plant.o: Plant.cpp Plant.h \
		PlantComponent.h \
		DeadState.h \
		PlantGrowthState.h \
		SeedState.h \
		GerminationState.h \
		SaplingState.h \
		MatureState.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		FertilizerMonitor.h \
		DeadMonitor.h \
		Water.h \
		HydratedState.h \
		NotHydratedState.h \
		Fertilizer.h \
		FertilizedState.h \
		NonFertilizerState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Plant.o Plant.cpp

build/obj/PlantCommand.o: PlantCommand.cpp PlantCommand.h \
		Command.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/PlantCommand.o PlantCommand.cpp

build/obj/PlantDecorator.o: PlantDecorator.cpp PlantDecorator.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/PlantDecorator.o PlantDecorator.cpp

build/obj/PlantFactory.o: PlantFactory.cpp PlantFactory.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		Plant.h \
		PlantComponent.h \
		FertilizerMonitor.h \
		DeadMonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/PlantFactory.o PlantFactory.cpp

build/obj/PlantGroup.o: PlantGroup.cpp PlantGroup.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/PlantGroup.o PlantGroup.cpp

build/obj/PlantMonitor.o: PlantMonitor.cpp PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/PlantMonitor.o PlantMonitor.cpp

build/obj/PlantSnapshot.o: PlantSnapshot.cpp PlantSnapshot.h \
		Plant.h \
		PlantComponent.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/PlantSnapshot.o PlantSnapshot.cpp

build/obj/ProxyGreenHouseInventory.o: ProxyGreenHouseInventory.cpp ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		RealGreenHouseInventory.h \
		QueryProduct.h \
		SeedState.h \
		Customer.h \
		QueryBuilder.h \
		SelectQueryBuilder.h \
		StaffHandler.h \
		Command.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/ProxyGreenHouseInventory.o ProxyGreenHouseInventory.cpp

build/obj/QueryBuilder.o: QueryBuilder.cpp QueryBuilder.h \
		Plant.h \
		PlantComponent.h \
		QueryProduct.h \
		PlantGrowthState.h \
		GreenHouseInventory.h \
		PlantSnapshot.h \
		Cactus.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		ProxyGreenHouseInventory.h \
		SeedState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/QueryBuilder.o QueryBuilder.cpp

build/obj/QueryProduct.o: QueryProduct.cpp QueryProduct.h \
		PlantGrowthState.h \
		Plant.h \
		PlantComponent.h \
		GreenHouseInventory.h \
		PlantSnapshot.h \
		Cactus.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		ProxyGreenHouseInventory.h \
		SeedState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/QueryProduct.o QueryProduct.cpp

build/obj/QueueIterator.o: QueueIterator.cpp QueueIterator.h \
		Command.h \
		StaffSystem.h \
		StaffHandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/QueueIterator.o QueueIterator.cpp

build/obj/RealGreenHouseInventory.o: RealGreenHouseInventory.cpp RealGreenHouseInventory.h \
		Plant.h \
		PlantComponent.h \
		Item.h \
		GreenHouseInventory.h \
		PlantSnapshot.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/RealGreenHouseInventory.o RealGreenHouseInventory.cpp

build/obj/Receipt.o: Receipt.cpp Receipt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Receipt.o Receipt.cpp

build/obj/RedPot.o: RedPot.cpp RedPot.h \
		PlantDecorator.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/RedPot.o RedPot.cpp

build/obj/Ribbon.o: Ribbon.cpp Ribbon.h \
		PlantDecorator.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Ribbon.o Ribbon.cpp

build/obj/Rose.o: Rose.cpp Rose.h \
		Plant.h \
		PlantComponent.h \
		PlantGrowthState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Rose.o Rose.cpp

build/obj/RoseFactory.o: RoseFactory.cpp RoseFactory.h \
		PlantFactory.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		Plant.h \
		PlantComponent.h \
		FertilizerMonitor.h \
		DeadMonitor.h \
		PlantGrowthState.h \
		Rose.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/RoseFactory.o RoseFactory.cpp

build/obj/SalesHandler.o: SalesHandler.cpp SalesHandler.h \
		StaffHandler.h \
		Command.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/SalesHandler.o SalesHandler.cpp

build/obj/SaplingState.o: SaplingState.cpp SaplingState.h \
		PlantGrowthState.h \
		MatureState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/SaplingState.o SaplingState.cpp

build/obj/Scent.o: Scent.cpp Scent.h \
		PlantDecorator.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Scent.o Scent.cpp

build/obj/SeedState.o: SeedState.cpp SeedState.h \
		PlantGrowthState.h \
		GerminationState.h \
		SaplingState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/SeedState.o SeedState.cpp

build/obj/SelectQueryBuilder.o: SelectQueryBuilder.cpp SelectQueryBuilder.h \
		QueryBuilder.h \
		Plant.h \
		PlantComponent.h \
		QueryProduct.h \
		PlantGrowthState.h \
		GreenHouseInventory.h \
		PlantSnapshot.h \
		Cactus.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		ProxyGreenHouseInventory.h \
		SeedState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/SelectQueryBuilder.o SelectQueryBuilder.cpp

build/obj/StaffHandler.o: StaffHandler.cpp StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		QueryBuilder.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/StaffHandler.o StaffHandler.cpp

build/obj/StaffSystem.o: StaffSystem.cpp StaffSystem.h \
		QueueIterator.h \
		Command.h \
		StaffHandler.h \
		PlantCommand.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/StaffSystem.o StaffSystem.cpp

build/obj/Sunflower.o: Sunflower.cpp Sunflower.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Sunflower.o Sunflower.cpp

build/obj/SunflowerFactory.o: SunflowerFactory.cpp SunflowerFactory.h \
		PlantFactory.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		Plant.h \
		PlantComponent.h \
		FertilizerMonitor.h \
		DeadMonitor.h \
		PlantGrowthState.h \
		Sunflower.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/SunflowerFactory.o SunflowerFactory.cpp

build/obj/Water.o: Water.cpp Water.h \
		PlantGrowthState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Water.o Water.cpp

build/obj/WaterCommand.o: WaterCommand.cpp WaterCommand.h \
		PlantCommand.h \
		Command.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/WaterCommand.o WaterCommand.cpp

build/obj/WaterHandler.o: WaterHandler.cpp WaterHandler.h \
		StaffHandler.h \
		Command.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/WaterHandler.o WaterHandler.cpp

build/obj/WaterMonitor.o: WaterMonitor.cpp WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		Plant.h \
		PlantComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/WaterMonitor.o WaterMonitor.cpp

build/obj/main.o: main.cpp Common/LoginDialog.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		RealGreenHouseInventory.h \
		Caretaker.h \
		OrderMemento.h \
		Order.h \
		PlantGroup.h \
		PriceStrategies.h \
		Receipt.h \
		StaffSystem.h \
		QueueIterator.h \
		Command.h \
		CustomerFacade.h \
		Customer.h \
		QueryBuilder.h \
		SelectQueryBuilder.h \
		PlantDecorator.h \
		NormalPrice.h \
		Save10Discount.h \
		BulkDiscount.h \
		GreenHouseFacade.h \
		PlantFactory.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		WaterCommand.h \
		PlantCommand.h \
		FertilizerMonitor.h \
		DeadMonitor.h \
		RoseFactory.h \
		SunflowerFactory.h \
		CactusFactory.h \
		WaterHandler.h \
		FertilizerHandler.h \
		DeadHandler.h \
		SalesHandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o main.cpp

build/obj/LoginDialog.o: Common/LoginDialog.cpp Common/LoginDialog.h \
		build/ui/ui_LoginDialog.h \
		CustomerWindows/CustomerMainWindow.h \
		CustomerFacade.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		Caretaker.h \
		OrderMemento.h \
		Order.h \
		PlantGroup.h \
		PriceStrategies.h \
		Receipt.h \
		Customer.h \
		QueryBuilder.h \
		SelectQueryBuilder.h \
		PlantDecorator.h \
		NormalPrice.h \
		Save10Discount.h \
		BulkDiscount.h \
		StaffWindows/StaffMainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/LoginDialog.o Common/LoginDialog.cpp

build/obj/CustomerMainWindow.o: CustomerWindows/CustomerMainWindow.cpp CustomerWindows/CustomerMainWindow.h \
		CustomerFacade.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		Caretaker.h \
		OrderMemento.h \
		Order.h \
		PlantGroup.h \
		PriceStrategies.h \
		Receipt.h \
		Customer.h \
		QueryBuilder.h \
		SelectQueryBuilder.h \
		PlantDecorator.h \
		NormalPrice.h \
		Save10Discount.h \
		BulkDiscount.h \
		build/ui/ui_CustomerMainWindow.h \
		CustomerWindows/ReturnOrderDialog.h \
		CustomerWindows/ReceiptDialog.h \
		Common/SharedInstances.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/CustomerMainWindow.o CustomerWindows/CustomerMainWindow.cpp

build/obj/ReturnOrderDialog.o: CustomerWindows/ReturnOrderDialog.cpp CustomerWindows/ReturnOrderDialog.h \
		build/ui/ui_ReturnOrderDialog.h \
		Common/SharedInstances.h \
		CustomerFacade.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		Caretaker.h \
		OrderMemento.h \
		Order.h \
		PlantGroup.h \
		PriceStrategies.h \
		Receipt.h \
		Customer.h \
		QueryBuilder.h \
		SelectQueryBuilder.h \
		PlantDecorator.h \
		NormalPrice.h \
		Save10Discount.h \
		BulkDiscount.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/ReturnOrderDialog.o CustomerWindows/ReturnOrderDialog.cpp

build/obj/ReceiptDialog.o: CustomerWindows/ReceiptDialog.cpp CustomerWindows/ReceiptDialog.h \
		Order.h \
		PlantGroup.h \
		PlantComponent.h \
		PriceStrategies.h \
		OrderMemento.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Receipt.h \
		build/ui/ui_ReceiptDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/ReceiptDialog.o CustomerWindows/ReceiptDialog.cpp

build/obj/StaffMainWindow.o: StaffWindows/StaffMainWindow.cpp StaffWindows/StaffMainWindow.h \
		build/ui/ui_StaffMainWindow.h \
		StaffWindows/PlantManagementWidget.h \
		GreenHouseFacade.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		PlantFactory.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		FertilizerMonitor.h \
		DeadMonitor.h \
		RoseFactory.h \
		SunflowerFactory.h \
		CactusFactory.h \
		WaterHandler.h \
		FertilizerHandler.h \
		DeadHandler.h \
		SalesHandler.h \
		StaffWindows/StaffManagementWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/StaffMainWindow.o StaffWindows/StaffMainWindow.cpp

build/obj/PlantManagementWidget.o: StaffWindows/PlantManagementWidget.cpp StaffWindows/PlantManagementWidget.h \
		GreenHouseFacade.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		PlantFactory.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		FertilizerMonitor.h \
		DeadMonitor.h \
		RoseFactory.h \
		SunflowerFactory.h \
		CactusFactory.h \
		WaterHandler.h \
		FertilizerHandler.h \
		DeadHandler.h \
		SalesHandler.h \
		build/ui/ui_PlantManagementWidget.h \
		Common/SharedInstances.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/PlantManagementWidget.o StaffWindows/PlantManagementWidget.cpp

build/obj/StaffManagementWidget.o: StaffWindows/StaffManagementWidget.cpp StaffWindows/StaffManagementWidget.h \
		GreenHouseFacade.h \
		ProxyGreenHouseInventory.h \
		GreenHouseInventory.h \
		PlantComponent.h \
		PlantSnapshot.h \
		Plant.h \
		Cactus.h \
		PlantGrowthState.h \
		Rose.h \
		Sunflower.h \
		Item.h \
		PlantFactory.h \
		WaterMonitor.h \
		PlantMonitor.h \
		StaffHandler.h \
		Command.h \
		StaffSystem.h \
		QueueIterator.h \
		WaterCommand.h \
		PlantCommand.h \
		FertilizerMonitor.h \
		DeadMonitor.h \
		RoseFactory.h \
		SunflowerFactory.h \
		CactusFactory.h \
		WaterHandler.h \
		FertilizerHandler.h \
		DeadHandler.h \
		SalesHandler.h \
		build/ui/ui_StaffManagementWidget.h \
		Common/SharedInstances.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/StaffManagementWidget.o StaffWindows/StaffManagementWidget.cpp

build/obj/qrc_resources.o: build/rcc/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/qrc_resources.o build/rcc/qrc_resources.cpp

build/obj/moc_LoginDialog.o: build/moc/moc_LoginDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_LoginDialog.o build/moc/moc_LoginDialog.cpp

build/obj/moc_CustomerMainWindow.o: build/moc/moc_CustomerMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_CustomerMainWindow.o build/moc/moc_CustomerMainWindow.cpp

build/obj/moc_ReturnOrderDialog.o: build/moc/moc_ReturnOrderDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_ReturnOrderDialog.o build/moc/moc_ReturnOrderDialog.cpp

build/obj/moc_ReceiptDialog.o: build/moc/moc_ReceiptDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_ReceiptDialog.o build/moc/moc_ReceiptDialog.cpp

build/obj/moc_StaffMainWindow.o: build/moc/moc_StaffMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_StaffMainWindow.o build/moc/moc_StaffMainWindow.cpp

build/obj/moc_PlantManagementWidget.o: build/moc/moc_PlantManagementWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_PlantManagementWidget.o build/moc/moc_PlantManagementWidget.cpp

build/obj/moc_StaffManagementWidget.o: build/moc/moc_StaffManagementWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_StaffManagementWidget.o build/moc/moc_StaffManagementWidget.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/PlantNurseryGUI/bin || mkdir -p $(INSTALL_ROOT)/opt/PlantNurseryGUI/bin
	$(QINSTALL_PROGRAM) bin/$(QMAKE_TARGET) $(INSTALL_ROOT)/opt/PlantNurseryGUI/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/PlantNurseryGUI/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/PlantNurseryGUI/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/PlantNurseryGUI/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

